### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Hanlian1** [yixinL7/PageSum#1]
我想知道作者的环境使用的是什么版本的transformers，您在环境要求中并未说明，我下载最新的transformers==4.26.1时会出现调用错误；
例如：from transformers.integrations import deepspeed_config, is_deepspeed_zero3_enabled
from transformers.file_utils import（cached_path,
                                                      hf_bucket_url,
                                                      is_offline_mode,
                                                      is_remote_url,）
希望作者可以帮我解答一下，谢谢

**Comment by yixinL7** [comment]
Please see https://github.com/yixinL7/PageSum/issues/2.
